version: '3'
services:
  web:
    build:
           context: .
           dockerfile: Dockerfile
    container_name: sts_web
    restart: always
    ports:
      - 8080:8080
      - 8024:8024
    # Link to containers in another services
    links:
      - db
    volumes:
      - $GOPATH
    networks:
          - mynet

  db:
    image: library/mysql:latest
    restart: always
    container_name: sts_db
    environment:
      MYSQL_ROOT_PASSWORD: alex21
    volumes:
          - ../../../../_local_mysql_data:/var/lib/mysql
    networks:
         - mynet


networks:
  mynet:
    driver: "bridge"
