version: '3'
services:
  front:
     build:
          context: ./admin_frontend
          dockerfile: Dockerfile
     container_name: sts_front
     restart: always
     ports:
        - 8217:8217
     links:
       - web
     volumes:
       - $GOPATH
     networks:
           - mynet
  web:
    build:
         context: .
         dockerfile: Dockerfile
    container_name: sts_web
    restart: always
    ports:
      - 8080:8080
    # Link to containers in another services
    links:
      - db
    volumes:
      - $GOPATH
    networks:
          - mynet

  doc:
     build:
          context: ./api
          dockerfile: Dockerfile
     container_name: sts_doc
     restart: always
     ports:
       - 8024:8080
     volumes:
       - $GOPATH
     networks:
          - mynet          
  db:
    build:
         context: ./db
         dockerfile: Dockerfile     
    restart: always
    container_name: sts_db
    networks:
         - mynet


networks:
  mynet:
    driver: "bridge"
